import Book from '@/applications/culture/Book'
import Category from '@/applications/culture/Category'
import BookRecord from '@/applications/culture/BookRecord'
import Category from '@/applications/culture/Category'
import Chapter from '@/applications/culture/Chapter'
import ChapterRecord from '@/applications/culture/ChapterRecord'
import Figure from '@/applications/culture/Figure'
import Headnote from '@/applications/culture/Headnote'
import Record from '@/applications/culture/Record'
import Shelf from '@/applications/culture/Shelf'
import ShelfBook from '@/applications/culture/ShelfBook'
import Tag from '@/applications/culture/Tag'
import TagInfo from '@/applications/culture/TagInfo'
import Reader from '@/applications/culture/Reader'

export default {Book, BookRecord, Category, Chapter, ChapterRecord, Figure, Headnote, Record, Shelf, ShelfBook, Tag, TagInfo, Reader}
