import Book from '@/applications/culture/Book'
import BookFigure from '@/applications/culture/BookFigure'
import BookPublish from '@/applications/culture/BookPublish'
import BookRecord from '@/applications/culture/BookRecord'
import BookSort from '@/applications/culture/BookSort'
import Calligrapher from '@/applications/culture/Calligrapher'
import Chapter from '@/applications/culture/Chapter'
import ChapterRecord from '@/applications/culture/ChapterRecord'
import Dateinfo from '@/applications/culture/Dateinfo'
import Dynasty from '@/applications/culture/Dynasty'
import Emperor from '@/applications/culture/Emperor'
import Figure from '@/applications/culture/Figure'
import FigureResume from '@/applications/culture/FigureResume'
import FigureTitle from '@/applications/culture/FigureTitle'
import Record from '@/applications/culture/Record'
import Rubbing from '@/applications/culture/Rubbing'
import RubbingDetail from '@/applications/culture/RubbingDetail'
import RubbingWord from '@/applications/culture/RubbingWord'
import Series from '@/applications/culture/Series'
import SeriesVolume from '@/applications/culture/SeriesVolume'
import Shelf from '@/applications/culture/Shelf'
import ShelfBook from '@/applications/culture/ShelfBook'
import Reader from '@/applications/culture/Reader'

export default {Book, BookFigure, BookPublish, BookRecord, BookSort, Calligrapher, Chapter, ChapterRecord, Dateinfo, Dynasty, Emperor, Figure, FigureResume, FigureTitle, Record, Rubbing, RubbingDetail, RubbingWord, Series, SeriesVolume, Shelf, ShelfBook, Reader}
