import AutoReply from '@/applications/third/AutoReply'
import CustomMenu from '@/applications/third/CustomMenu'
import Material from '@/applications/third/Material'
import MaterialArticle from '@/applications/third/MaterialArticle'
import Message from '@/applications/third/Message'
import MessageData from '@/applications/third/MessageData'
import Payment from '@/applications/third/Payment'
import Plat from '@/applications/third/Plat'
import Qrcode from '@/applications/third/Qrcode'
import Service from '@/applications/third/Service'
import TemplateMessage from '@/applications/third/TemplateMessage'
import TemplateRecord from '@/applications/third/TemplateRecord'
import UserPlat from '@/applications/third/UserPlat'

export default {AutoReply, CustomMenu, Material, MaterialArticle, Message, MessageData, Payment, Plat, Qrcode, Service, TemplateMessage, TemplateRecord, UserPlat}