import Account from '@/applications/paytrade/Account'
import Activity from '@/applications/paytrade/Activity'
import Cart from '@/applications/paytrade/Cart'
import Coupon from '@/applications/paytrade/Coupon'
import CouponSort from '@/applications/paytrade/CouponSort'
import LogisticsCompany from '@/applications/paytrade/LogisticsCompany'
import OrderAddress from '@/applications/paytrade/OrderAddress'
import OrderAfter from '@/applications/paytrade/OrderAfter'
import OrderExpress from '@/applications/paytrade/OrderExpress'
import OrderGoods from '@/applications/paytrade/OrderGoods'
import OrderInfo from '@/applications/paytrade/OrderInfo'
import OrderStatus from '@/applications/paytrade/OrderStatus'
import PayRecord from '@/applications/paytrade/PayRecord'
import Showoff from '@/applications/paytrade/Showoff'
import ShowoffComment from '@/applications/paytrade/ShowoffComment'
import UserPaytrade from '@/applications/paytrade/UserPaytrade'
import UserPreferential from '@/applications/paytrade/UserPreferential'

export default {Account, Activity, Cart, Coupon, CouponSort, LogisticsCompany, OrderAddress, OrderAfter, OrderExpress, OrderGoods, OrderInfo, OrderStatus, PayRecord, Showoff, ShowoffComment, UserPaytrade, UserPreferential}