import Article from '@/applications/infocms/Article'
import Brand from '@/applications/infocms/Brand'
import Category from '@/applications/infocms/Category'
import Human from '@/applications/infocms/Human'
import Knowledge from '@/applications/infocms/Knowledge'
import Pet from '@/applications/infocms/Pet'
import PetArticle from '@/applications/infocms/PetArticle'
import PetInfosort from '@/applications/infocms/PetInfosort'
import PetPetsort from '@/applications/infocms/PetPetsort'
import PetSort from '@/applications/infocms/PetSort'
import Product from '@/applications/infocms/Product'
import Store from '@/applications/infocms/Store'
import Subject from '@/applications/infocms/Subject'
import Website from '@/applications/infocms/Website'

export default {Article, Brand, Category, Human, Knowledge, Pet, PetArticle, PetInfosort, PetPetsort, PetSort, Product, Store, Subject, Website}
