import Article from '@/applications/infocms/Article'
import Attachment from '@/applications/infocms/Attachment'
import Brand from '@/applications/infocms/Brand'
import Calligrapher from '@/applications/infocms/Calligrapher'
import Category from '@/applications/infocms/Category'
import CultureArticle from '@/applications/infocms/CultureArticle'
import CultureCategory from '@/applications/infocms/CultureCategory'
import Human from '@/applications/infocms/Human'
import Knowledge from '@/applications/infocms/Knowledge'
import Pet from '@/applications/infocms/Pet'
import PetArticle from '@/applications/infocms/PetArticle'
import PetInfosort from '@/applications/infocms/PetInfosort'
import PetPetsort from '@/applications/infocms/PetPetsort'
import PetSort from '@/applications/infocms/PetSort'
import Product from '@/applications/infocms/Product'
import Rubbing from '@/applications/infocms/Rubbing'
import RubbingDetail from '@/applications/infocms/RubbingDetail'
import Store from '@/applications/infocms/Store'
import Subject from '@/applications/infocms/Subject'
import Website from '@/applications/infocms/Website'

export default {Article, Attachment, Brand, Calligrapher, Category, CultureArticle, CultureCategory, Human, Knowledge, Pet, PetArticle, PetInfosort, PetPetsort, PetSort, Product, Rubbing, RubbingDetail, Store, Subject, Website}