import Article from '@/applications/infocms/Article'
import Category from '@/applications/infocms/Category'
import Group from '@/applications/infocms/Group'
import GroupSubject from '@/applications/infocms/GroupSubject'
import Headnote from '@/applications/infocms/Headnote'
import InfoMark from '@/applications/infocms/InfoMark'
import MaterialPseudo from '@/applications/infocms/MaterialPseudo'
import MaterialSource from '@/applications/infocms/MaterialSource'
import MicroHeadline from '@/applications/infocms/MicroHeadline'
import Navsort from '@/applications/infocms/Navsort'
import NavsortInfo from '@/applications/infocms/NavsortInfo'
import Position from '@/applications/infocms/Position'
import PositionInfo from '@/applications/infocms/PositionInfo'
import Subject from '@/applications/infocms/Subject'
import Topic from '@/applications/infocms/Topic'

export default {Article, Category, Group, GroupSubject, Headnote, InfoMark, MaterialPseudo, MaterialSource, MicroHeadline, Navsort, NavsortInfo, Position, PositionInfo, Subject, Topic}