import Attachment from '@/applications/passport/Attachment'
import AttachmentInfo from '@/applications/passport/AttachmentInfo'
import AttachmentPath from '@/applications/passport/AttachmentPath'
import AttachmentVideo from '@/applications/passport/AttachmentVideo'
import Manager from '@/applications/passport/Manager'
import Managerlog from '@/applications/passport/Managerlog'
import Permission from '@/applications/passport/Permission'
import Resource from '@/applications/passport/Resource'
import Role from '@/applications/passport/Role'
import RoleManager from '@/applications/passport/RoleManager'
import RolePermission from '@/applications/passport/RolePermission'
import Faq from '@/applications/passport/Faq'
import Feedback from '@/applications/passport/Feedback'
import Group from '@/applications/passport/Group'
import Realname from '@/applications/passport/Realname'
import Region from '@/applications/passport/Region'
import User from '@/applications/passport/User'
import UserAddress from '@/applications/passport/UserAddress'
import UserGroup from '@/applications/passport/UserGroup'
import UserScore from '@/applications/passport/UserScore'

export default {Attachment, AttachmentInfo, AttachmentPath, AttachmentVideo, Manager, Managerlog, Permission, Resource, Role, RoleManager, RolePermission, Faq, Feedback, Group, Realname, Region, User, UserAddress, UserGroup, UserScore}
